image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'Install pre-requisites' # runs during prebuild
    command: jupyter-lab --NotebookApp.token="" --NotebookApp.ip="0.0.0.0" --NotebookApp.allow_origin="*" --NotebookApp.open_browser=False
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-preview
